export const AI_MODULE = 'M2' as const
export const AI_OPERATION = 'generate' as const
export const AI_PROVIDER = 'openai' as const
export const AI_MODEL_ID = 'gpt-5.6-luna' as const
export const AI_MODEL_DISPLAY_NAME = 'GPT-5.6 Luna' as const
export const AI_PROVIDER_DISPLAY_NAME = 'OpenAI' as const
export const M3_MODULE = 'M3' as const
export const M3_OPERATION = 'adapt' as const
export const M3_ADAPT_OPERATION = 'content.adapt' as const
export const M4_MODULE = 'M4' as const
export const M4_OPERATION = 'brand_check' as const
export const M4_BRAND_CHECK_OPERATION = 'content.brand-check' as const
export const AI_LANGUAGES = ['English', 'Indonesian'] as const
export type AiLanguage = (typeof AI_LANGUAGES)[number]
export const AI_MODES = ['real', 'demo'] as const
export type AiMode = (typeof AI_MODES)[number]
export const AI_STATUSES = ['pending', 'success', 'failed', 'stale'] as const
export type AiRequestStatus = (typeof AI_STATUSES)[number]
export const PROMPT_STATUSES = ['active', 'retired'] as const
export type PromptStatus = (typeof PROMPT_STATUSES)[number]
export const OUTPUT_SCHEMA_VERSION = 'm2.generate.v1' as const
export const M3_OUTPUT_SCHEMA_VERSION = 'm3.adapt.v1' as const
export const M4_OUTPUT_SCHEMA_VERSION = 'm4.brand_check.v1' as const
export const PROMPT_VERSION = 'v1' as const

export const AI_SETTINGS_OPERATION = 'ai-settings.update'
export const AI_GENERATE_OPERATION = 'content.generate'
