export const AI_MODULE = 'M2' as const
export const AI_OPERATION = 'generate' as const
export const AI_PROVIDER = 'openai' as const
export const AI_MODEL_ID = 'gpt-5.6-luna' as const
export const AI_MODEL_DISPLAY_NAME = 'GPT-5.6 Luna' as const
export const AI_PROVIDER_DISPLAY_NAME = 'OpenAI' as const
export const M3_MODULE = 'M3' as const
export const M3_OPERATION = 'adapt' as const
export const M3_ADAPT_OPERATION = 'content.adapt' as const
export const M4_MODULE = 'M4' as const
export const M4_OPERATION = 'brand_check' as const
export const M4_BRAND_CHECK_OPERATION = 'content.brand-check' as const
export const AI_LANGUAGES = ['English', 'Indonesian'] as const
export type AiLanguage = (typeof AI_LANGUAGES)[number]
export const AI_MODES = ['real', 'demo'] as const
export type AiMode = (typeof AI_MODES)[number]
export const AI_STATUSES = ['pending', 'success', 'failed', 'stale'] as const
export type AiRequestStatus = (typeof AI_STATUSES)[number]
export const PROMPT_STATUSES = ['active', 'retired'] as const
export type PromptStatus = (typeof PROMPT_STATUSES)[number]
export const OUTPUT_SCHEMA_VERSION = 'm2.generate.v1' as const
export const M3_OUTPUT_SCHEMA_VERSION = 'm3.adapt.v1' as const
export const M4_OUTPUT_SCHEMA_VERSION = 'm4.brand_check.v1' as const
export const CREATIVE_REFERENCE_OUTPUT_SCHEMA_VERSION = 'm2.creative_reference_concepts.v1' as const
export const PROMPT_VERSION = 'v1' as const

export const AI_SETTINGS_OPERATION = 'ai-settings.update'
export const AI_GENERATE_OPERATION = 'content.generate'
export const CREATIVE_REFERENCE_MODULE = 'M2'
export const CREATIVE_REFERENCE_CONCEPT_OPERATION = 'creative_reference.concepts'
export const CREATIVE_REFERENCE_IMAGE_OPERATION = 'creative_reference.image'
export const CREATIVE_REFERENCE_PROMPT_VERSION = 'creative-reference-v1'
export const CREATIVE_REFERENCE_PROMPT_REFERENCE = 'm2.creative_reference_concepts.v1'
export const M2_DISCOVERY_OPERATION = 'idea.discovery.web_search' as const
export const M2_DISCOVERY_OUTPUT_SCHEMA_VERSION = 'm2.idea_discovery_web_search.v1' as const
export const M2_DISCOVERY_PROMPT_VERSION = 'idea-discovery-web-search-v1' as const
export const M2_DISCOVERY_PROMPT_REFERENCE = 'm2.idea_discovery_web_search.v1' as const
export const M2_TELEGRAM_CHAT_OPERATION = 'telegram.ideation.chat' as const
export const M2_TELEGRAM_STRUCTURE_OPERATION = 'telegram.ideation.structure' as const
export const M2_TELEGRAM_CHAT_OUTPUT_SCHEMA_VERSION = 'm2.telegram_ideation_chat.v1' as const
export const M2_TELEGRAM_STRUCTURE_OUTPUT_SCHEMA_VERSION = 'm2.telegram_ideation_structure.v1' as const
export const M2_TELEGRAM_CHAT_PROMPT_VERSION = 'telegram-ideation-chat-v1' as const
export const M2_TELEGRAM_STRUCTURE_PROMPT_VERSION = 'telegram-ideation-structure-v1' as const
export const M2_TELEGRAM_CHAT_PROMPT_REFERENCE = 'm2.telegram_ideation_chat.v1' as const
export const M2_TELEGRAM_STRUCTURE_PROMPT_REFERENCE = 'm2.telegram_ideation_structure.v1' as const
